Remove using pkg/errors #211
simplesurance/baur pull request #213
Opened 2020-10-09 12:17 UTC by u5surf

Fixes #211 

- using Golangs errors wrapper `fmt.Errorf %w` 
- `errors.Is` is used Golang standard `errors`
- Also remove `go.mod` and vendor directory

2020-10-09 12:35 UTC, fho requested changes
looks good,
I added some suggestions that needs to be applied.
CI is currently also failing because there seems to be still an import left but the pkg does not exist in vendor directory anymore:

```
* building baur
vendor/github.com/simplesurance/baur/app.go:9:2: cannot find package "." in:
	/home/circleci/baur/vendor/github.com/pkg/errors
make: *** [Makefile:19: baur] Error 1
```

2020-10-09 12:35 UTC, fho commented on internal/digest/digest.go
> +		return nil, fmt.Errorf("invalid format, must contain exactly 1 ':'")
please use `fmt.Errorf()` only when specifying format strings, otherwise `errors.New`

2020-10-09 12:35 UTC, fho commented on internal/digest/digest.go
> +		return nil, fmt.Errorf("unsupported format %%q")
```suggestion
		return nil, fmt.Errorf("unsupported format %q", a)
```

2020-10-09 12:35 UTC, fho commented on internal/digest/sha384/sha384.go
> +		return fmt.Errorf("writing to hash stream failed")
```suggestion
		return fmt.Errorf("writing to hash stream failed: %w", err)
```
wrapping the error is missing here

2020-10-09 12:35 UTC, fho commented on internal/upload/filecopy/filecopy.go
> +			return "", fmt.Errorf("creating directory '%s' failed: %w", destDir, err)
```suggestion
			return "", fmt.Errorf("creating directory %s failed: %w", destDir, err)
```

2020-10-09 12:35 UTC, fho commented on internal/upload/filecopy/filecopy.go
> +			return "", fmt.Errorf("%s is not a directory :%w", destDir, err)
err is nil here, that was buggy before, we do not need to wrap nil
```suggestion
			return "", fmt.Errorf("%s is not a directory", destDir,)
```

2020-10-09 12:35 UTC, fho commented on internal/upload/filecopy/filecopy.go
> +		return "", fmt.Errorf("'%s' exist but is not a regular file :%w", dst, err)
same here 
```suggestion
		return "", fmt.Errorf("'%s' exist but is not a regular file", dst)
```

2020-10-09 12:35 UTC, fho commented on internal/vcs/git/git.go
> +		return "", fmt.Errorf("executing git rev-parse HEAD failed, no Stdout output: %w", err)
```suggestion
		return "", errors.New("executing git rev-parse HEAD failed, no Stdout output)
```

2020-10-09 12:35 UTC, fho commented on internal/version/version.go
> +		return fmt.Errorf("parsing version '%s' failed: %w", Version, err)
```suggestion
		return fmt.Errorf("parsing version %q failed: %w", Version, err)
```

2020-10-10 07:43 UTC, u5surf commented
@fho Thank you for your reviewing, I had fixed all following your comments.

2020-10-12 07:17 UTC, fho commented
@u5surf the CI checks are still failing, you can see the status in your PR:
![image](https://user-images.githubusercontent.com/514535/95716132-3b3fc100-0c6b-11eb-8e24-a35df45fc5bc.png)
If you click on "Details" you can see why they are failing.
```
#!/bin/bash -eo pipefail
make baur

* building baur
vendor/github.com/simplesurance/baur/app.go:9:2: cannot find package "." in:
	/home/circleci/baur/vendor/github.com/pkg/errors
make: *** [Makefile:19: baur] Error
```
They must be successful before we can merge it.

If it's not clear what the issue is I can help :-)

2020-10-12 14:27 UTC, u5surf commented
@fho 
Hi, 
I suppose that CI has failed because `pkg/errors` has removed, in spite of that `baur` in the vendor directory( may be it is in HEAD)  needs `pkg/errors`.

2020-10-12 14:29 UTC, fho commented
@u5surf you are right, if it's still needed as indirect dependency we can not remove it from go.mod and vendor/

2020-10-12 14:31 UTC, u5surf commented
@fho 
OK, I will revert removing it from go.mod and vendor/

2020-10-13 09:17 UTC, fho approved these changes

2020-10-13 09:19 UTC, merged

2020-10-13 09:19 UTC, fho commented
@u5surf thanks a lot for the PR! :-)